# Generated by Django 4.1.3 on 2022-12-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_messages_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
