# Generated by Django 4.1.3 on 2022-12-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
